import os
import shutil
import subprocess

# Subprocess wait timeout in seconds; configurable via EVAL_RUNNER_TIMEOUT env var.
try:
    _RUNNER_TIMEOUT: int = int(os.environ.get("EVAL_RUNNER_TIMEOUT", "300"))
except ValueError:
    _RUNNER_TIMEOUT = 300

# ============================================================================
# Base Runner
# ============================================================================


class AgentRunner:
    """
    Abstract base class for all headless AI agent evaluators.
    """

    def run(self, prompt: str, workspace_path: str) -> str:
        """
        Executes a prompt inside a specified workspace and returns the console output.

        Args:
            prompt (str): The instructions to provide to the agent.
            workspace_path (str): The directory context for the agent's execution.

        Returns:
            str: The final stdout and stderr output generated by the agent.
        """
        raise NotImplementedError("Runner must implement run method")


# ============================================================================
# Copilot Runner
# ============================================================================


class CopilotRunner(AgentRunner):
    """
    Executes the @github/copilot NPM package in a headless, non-interactive environment
    for evaluating skill performance.
    """

    def run(self, prompt: str, workspace_path: str) -> str:
        """
        Executes a prompt via the Copilot CLI and returns the console output.

        Args:
            prompt (str): The instructions to provide to the agent.
            workspace_path (str): The directory context for the agent's execution.

        Returns:
            str: The final stdout output generated by the agent.
        """
        print(f"\n[Copilot Runner] Executing in {workspace_path}...")

        env = os.environ.copy()
        env.pop("AWS_PROFILE", None)
        env.pop("AWS_DEFAULT_PROFILE", None)
        env["CI"] = "true"
        env["GH_PAGER"] = ""
        env["GH_PROMPT_DISABLED"] = "1"
        env["NO_COLOR"] = "1"
        env["PWD"] = workspace_path

        if "PYTHONPATH" not in env:
            raise OSError("PYTHONPATH must be set in the environment for CopilotRunner to function properly.")

        prompt = (
            f"{prompt} If the task fails or you encounter an error, STOP "
            "immediately and report the error without trying other "
            "workarounds or methods."
        )
        # We use --allow-all to grant permissions required for non-interactive execution
        # and --no-color + --no-ask-user to force static automation.
        args = ["copilot", "-p", prompt, "--allow-all", "--no-color", "--no-ask-user"]

        print("Starting process...", flush=True)
        process = subprocess.Popen(
            args,
            cwd=workspace_path,
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            stdin=subprocess.DEVNULL,
        )

        output_lines = []
        if process.stdout is None:
            raise RuntimeError("subprocess.Popen returned None stdout despite stdout=PIPE")
        for line in process.stdout:
            print(f"CLI OUTPUT: {line.strip()}", flush=True)
            output_lines.append(line)

        try:
            process.wait(timeout=_RUNNER_TIMEOUT)
        except subprocess.TimeoutExpired:
            process.kill()
            process.wait()
            error_msg = f"\n[Copilot Runner Error] Timed out after {_RUNNER_TIMEOUT}s!"
            print(error_msg, flush=True)
            return error_msg

        return "".join(output_lines)


# ============================================================================
# Claude Code Runner
# ============================================================================


class ClaudeCodeRunner(AgentRunner):
    """
    Executes the Claude Code CLI in a headless, non-interactive environment
    for evaluating skill performance.
    """

    def run(self, prompt: str, workspace_path: str) -> str:
        """
        Executes a prompt via the Claude Code CLI and returns the console output.

        Enterprise OAuth is supported: when ``claude`` is on PATH and the user is
        authenticated via ``claude login``, no API key is required. ``ANTHROPIC_API_KEY``
        is only needed for CI/CD environments where OAuth is unavailable. This method
        therefore invokes the CLI unconditionally and lets the subprocess surface any
        auth error naturally.

        Args:
            prompt (str): The instructions to provide to the agent.
            workspace_path (str): The directory context for the agent's execution.

        Returns:
            str: The final stdout output generated by the agent.
        """
        print(f"\n[Claude Code Runner] Executing in {workspace_path}...")

        args = [
            "claude",
            "-p",
            prompt,
            "--output-format",
            "text",
            "--max-turns",
            os.environ.get("CLAUDE_MAX_TURNS", "25"),
            "--dangerously-skip-permissions",
            "--setting-sources",
            "user",
        ]

        env = os.environ.copy()
        env.pop("AWS_PROFILE", None)
        env.pop("AWS_DEFAULT_PROFILE", None)
        env["CI"] = "true"
        env["NO_COLOR"] = "1"

        process = subprocess.Popen(
            args,
            cwd=workspace_path,
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            stdin=subprocess.DEVNULL,
        )

        output_lines = []
        if process.stdout is None:
            raise RuntimeError("subprocess.Popen returned None stdout despite stdout=PIPE")
        for line in process.stdout:
            output_lines.append(line)

        try:
            process.wait(timeout=_RUNNER_TIMEOUT)
        except subprocess.TimeoutExpired:
            process.kill()
            process.wait()
            return f"\n[Claude Code Runner Error] Timed out after {_RUNNER_TIMEOUT}s!"

        if process.returncode != 0:
            return f"\n[Claude Code Runner Error] Return Code: {process.returncode}\nOutput: {''.join(output_lines)}"

        return "".join(output_lines)


# ============================================================================
# Gemini Runner
# ============================================================================


class GeminiRunner(AgentRunner):
    """
    Executes the Gemini CLI in a headless, non-interactive environment
    for evaluating skill performance.
    """

    def run(self, prompt: str, workspace_path: str) -> str:
        """
        Executes a prompt via the Gemini CLI and returns the console output.

        Args:
            prompt (str): The instructions to provide to the agent.
            workspace_path (str): The directory context for the agent's execution.

        Returns:
            str: The final stdout output generated by the agent.
        """
        print(f"\n[Gemini Runner] Executing in {workspace_path}...")

        args = ["gemini"]
        gemini_model = os.environ.get("GEMINI_MODEL")
        if gemini_model:
            args.extend(["-m", gemini_model])
        args.extend(["-p", prompt, "--yolo", "--output-format", "text"])

        env = os.environ.copy()
        env.pop("AWS_PROFILE", None)
        env.pop("AWS_DEFAULT_PROFILE", None)
        env["CI"] = "true"
        env["NO_COLOR"] = "1"

        process = subprocess.Popen(
            args,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            stdin=subprocess.DEVNULL,
            text=True,
            cwd=workspace_path,
            env=env,
        )

        output_lines = []
        if process.stdout is None:
            raise RuntimeError("subprocess.Popen returned None stdout despite stdout=PIPE")
        for line in process.stdout:
            output_lines.append(line)

        try:
            process.wait(timeout=_RUNNER_TIMEOUT)
        except subprocess.TimeoutExpired:
            process.kill()
            process.wait()
            return f"\n[Gemini Runner Error] Timed out after {_RUNNER_TIMEOUT}s!"

        if process.returncode != 0:
            return f"\n[Gemini Runner Error] Return Code: {process.returncode}\nOutput: {''.join(output_lines)}"

        return "".join(output_lines)


# ============================================================================
# Codex Runner
# ============================================================================


class CodexRunner(AgentRunner):
    """
    Executes the Codex CLI in a headless, non-interactive environment
    for evaluating skill performance.
    """

    def run(self, prompt: str, workspace_path: str) -> str:
        """
        Executes a prompt via the Codex CLI and returns the console output.

        Args:
            prompt (str): The instructions to provide to the agent.
            workspace_path (str): The directory context for the agent's execution.

        Returns:
            str: The final stdout output generated by the agent.
        """
        print(f"\n[Codex Runner] Executing in {workspace_path}...")

        args = ["codex"]
        codex_model = os.environ.get("CODEX_MODEL")
        if codex_model:
            args.extend(["-m", codex_model])
        args.extend(["exec", prompt, "--sandbox", "workspace-write", "--color", "never"])

        env = os.environ.copy()
        env.pop("AWS_PROFILE", None)
        env.pop("AWS_DEFAULT_PROFILE", None)
        env["CI"] = "true"
        env["NO_COLOR"] = "1"

        process = subprocess.Popen(
            args,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            stdin=subprocess.DEVNULL,
            text=True,
            cwd=workspace_path,
            env=env,
        )

        output_lines = []
        if process.stdout is None:
            raise RuntimeError("subprocess.Popen returned None stdout despite stdout=PIPE")
        for line in process.stdout:
            output_lines.append(line)

        try:
            process.wait(timeout=_RUNNER_TIMEOUT)
        except subprocess.TimeoutExpired:
            process.kill()
            process.wait()
            return f"\n[Codex Runner Error] Timed out after {_RUNNER_TIMEOUT}s!"

        if process.returncode != 0:
            return f"\n[Codex Runner Error] Return Code: {process.returncode}\nOutput: {''.join(output_lines)}"

        return "".join(output_lines)


# ============================================================================
# Runner Registry and Factory
# ============================================================================

# Registry columns: (cli_name, runner_class, api_key_env_var, cli_sufficient)
# cli_sufficient=True means the CLI on PATH alone is enough (e.g. Claude with enterprise OAuth).
# cli_sufficient=False means a token/API key is required even if the binary exists.
_RUNNER_REGISTRY: list[tuple[str, type[AgentRunner], str, bool]] = [
    ("claude", ClaudeCodeRunner, "ANTHROPIC_API_KEY", True),  # CLI on PATH works via OAuth
    ("copilot", CopilotRunner, "COPILOT_GITHUB_TOKEN", False),  # headless needs token
    ("gemini", GeminiRunner, "GEMINI_API_KEY", False),  # headless needs token
    ("codex", CodexRunner, "OPENAI_API_KEY", False),  # headless needs token
]


def get_runner(runner_type: str | None = None) -> AgentRunner:
    """
    Factory function to retrieve an AgentRunner instance.

    If ``runner_type`` is provided, uses a direct lookup (backward compatibility).
    If ``runner_type`` is ``None``, auto-detects in the following order:

    1. ``EVAL_RUNNER`` env-var override.
    2. Registry priority scan:
       - For runners with ``cli_sufficient=True`` (Claude): the CLI binary on PATH is
         checked first (covers local dev with enterprise OAuth), then the API key env var
         (covers CI/CD).
       - For all other runners: only the API key env var is checked, because the CLI
         binary alone is insufficient for headless execution.

    Args:
        runner_type (str | None, optional): The name of the agent runner to load.
            If None, auto-detects from the environment. Defaults to None.

    Returns:
        AgentRunner: The instantiated agent evaluator.

    Raises:
        KeyError: If ``runner_type`` or ``EVAL_RUNNER`` specifies an unknown runner name.
        RuntimeError: If no suitable CLI binary or API key is found and runner_type is None.
    """
    _runners: dict[str, type[AgentRunner]] = {name: cls for name, cls, _, _ in _RUNNER_REGISTRY}

    if runner_type is not None:
        return _runners[runner_type]()

    # Check EVAL_RUNNER env var override first
    eval_runner_env = os.environ.get("EVAL_RUNNER")
    if eval_runner_env:
        return _runners[eval_runner_env]()

    # Auto-detect from registry in priority order
    for name, runner_cls, env_var, cli_sufficient in _RUNNER_REGISTRY:
        if cli_sufficient and shutil.which(name):
            return runner_cls()
        if os.environ.get(env_var):
            return runner_cls()

    raise RuntimeError(
        "No agent CLI or API key found. Set ANTHROPIC_API_KEY, COPILOT_GITHUB_TOKEN, GEMINI_API_KEY, or OPENAI_API_KEY, or install a supported CLI."
    )
